### ISSUE TITLE
[feature request] prompt-answer history 

### ISSUE THREAD

**Issue by floppydisken** [David-Kunz/gen.nvim#39]
Sometimes I just want to go back in the history for each prompt I've asked in order to refetch whatever response the model has come up with.

An example use-case for me was fixing a Makefile in which I asked for suggestion for a specific thing. I copied what I needed but ended up having to reask in order to fetch the rest. That seemed like unnecessary wait and compute.

**Comment by David-Kunz** [comment]
Hi @floppydisken ,

Thank you for the suggestion, good point! This PR https://github.com/David-Kunz/gen.nvim/pull/36 uses splits instead of windows, that might be better and the user can decide to close the split or keep it open.

Do you think that would be sufficient?

Thanks and best regards,
David

**Comment by David-Kunz** [comment]
Hi @floppydisken ,

You can now set `display_mode = 'split'` and keep your split open.

Best regards,
David

**Comment by floppydisken** [comment]
Yes probably. I'll test it. Thank you for the quick response @David-Kunz!
